# Generated by Django 2.1.7 on 2019-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrdersNC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.BigIntegerField()),
                ('gpay_ph_no', models.BigIntegerField()),
                ('block', models.CharField(max_length=15)),
                ('item_id', models.TextField()),
                ('item_name', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaidOrdersNC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.BigIntegerField()),
                ('gpay_ph_no', models.BigIntegerField()),
                ('block', models.CharField(max_length=15)),
                ('item_id', models.TextField()),
                ('item_name', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaidOrdersNC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.BigIntegerField()),
                ('gpay_ph_no', models.BigIntegerField()),
                ('block', models.CharField(max_length=15)),
                ('item_id', models.TextField()),
                ('item_name', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
