# Generated by Django 3.0.7 on 2020-06-11 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NC1Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('veg', models.BooleanField(default=True)),
                ('currently_present', models.BooleanField()),
                ('filter', models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items'), (3, 'Sandwiches Bar')])),
            ],
            options={
                'verbose_name_plural': 'Menu items of Block 3 Night Canteen',
            },
        ),
        migrations.CreateModel(
            name='NC2Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('veg', models.BooleanField(default=True)),
                ('currently_present', models.BooleanField()),
                ('filter', models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items'), (3, 'Sandwiches Bar')])),
            ],
            options={
                'verbose_name_plural': 'Menu items of Block 7 Night Canteen',
            },
        ),
        migrations.CreateModel(
            name='NC3Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('veg', models.BooleanField(default=True)),
                ('currently_present', models.BooleanField()),
                ('filter', models.IntegerField(choices=[(1, 'Noodle Items'), (2, 'Rice Items')])),
            ],
            options={
                'verbose_name_plural': "Menu items of Girl's Block Night Canteen",
            },
        ),
        migrations.CreateModel(
            name='PaidOrdersNC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.BigIntegerField()),
                ('gpay_ph_no', models.BigIntegerField()),
                ('block', models.CharField(max_length=15)),
                ('order_comments', models.TextField(blank=True, null=True)),
                ('filters', models.CharField(choices=[('a', 'Pending'), ('b', 'Delivered'), ('c', 'Rejected')], default='a', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "List of orders created - Girl's Block Night Canteen",
            },
        ),
        migrations.CreateModel(
            name='PaidOrdersNC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.BigIntegerField()),
                ('gpay_ph_no', models.BigIntegerField()),
                ('block', models.CharField(max_length=15)),
                ('order_comments', models.TextField(blank=True, null=True)),
                ('filters', models.CharField(choices=[('a', 'Pending'), ('b', 'Delivered'), ('c', 'Rejected')], default='a', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'List of orders created - Block 7 Night Canteen',
            },
        ),
        migrations.CreateModel(
            name='PaidOrdersNC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.BigIntegerField()),
                ('gpay_ph_no', models.BigIntegerField()),
                ('block', models.CharField(max_length=15)),
                ('order_comments', models.TextField(blank=True, null=True)),
                ('filters', models.CharField(choices=[('a', 'Pending'), ('b', 'Delivered'), ('c', 'Rejected')], default='a', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'List of orders created - Block 3 Night Canteen',
            },
        ),
        migrations.CreateModel(
            name='NC3OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='night_owl.PaidOrdersNC3')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='night_owl.NC3Products')),
            ],
        ),
        migrations.CreateModel(
            name='NC2OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='night_owl.PaidOrdersNC2')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='night_owl.NC2Products')),
            ],
        ),
        migrations.CreateModel(
            name='NC1OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='night_owl.PaidOrdersNC1')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='night_owl.NC1Products')),
            ],
        ),
    ]
