# Generated by Django 3.0.7 on 2020-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidordersnc1',
            name='order_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
