# Generated by Django 3.0.7 on 2020-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0002_paidordersnc1_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidordersnc2',
            name='order_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidordersnc3',
            name='order_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
