# Generated by Django 2.1.5 on 2019-03-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0003_auto_20190314_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='NC1Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NC2Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NC3Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='nc1products',
            name='veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nc2products',
            name='veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nc3products',
            name='veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nc1products',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='night_owl.NC1Filters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nc2products',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='night_owl.NC2Filters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nc3products',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='night_owl.NC3Filters'),
            preserve_default=False,
        ),
    ]
