# Generated by Django 2.1.5 on 2019-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0009_auto_20190321_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='nc1products',
            name='filters',
            field=models.CharField(choices=[('a', 'Hot and Cold Beverages'), ('b', 'Dosa Items')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nc2products',
            name='filters',
            field=models.CharField(choices=[('a', 'Hot and Cold Beverages'), ('b', 'Dosa Items')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nc3products',
            name='filters',
            field=models.CharField(choices=[('a', 'Hot and Cold Beverages'), ('b', 'Dosa Items')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
