# Generated by Django 2.1.5 on 2019-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0010_auto_20190321_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc1products',
            name='filters',
            field=models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nc2products',
            name='filters',
            field=models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nc3products',
            name='filters',
            field=models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items')], max_length=1),
        ),
    ]
