# Generated by Django 2.1.5 on 2019-03-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0013_auto_20190321_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nc1products',
            old_name='filters',
            new_name='filter',
        ),
        migrations.RenameField(
            model_name='nc2products',
            old_name='filters',
            new_name='filter',
        ),
        migrations.RenameField(
            model_name='nc3products',
            old_name='filters',
            new_name='filter',
        ),
    ]
