# Generated by Django 2.1.7 on 2019-03-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night_owl', '0016_auto_20190322_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc3products',
            name='filter',
            field=models.IntegerField(choices=[(1, 'Noodle Items'), (2, 'Rice Items')]),
        ),
    ]
