# Generated by Django 2.1.7 on 2019-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190322_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc1products',
            name='filter',
            field=models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items'), (3, 'Sandwiches Bar')]),
        ),
        migrations.AlterField(
            model_name='nc2products',
            name='filter',
            field=models.IntegerField(choices=[(1, 'Hot and Cold Beverages'), (2, 'Dosa Items'), (3, 'Sandwiches Bar')]),
        ),
    ]
