# Generated by Django 2.1.5 on 2019-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190310_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='nc_id',
            field=models.IntegerField(default=1),
        ),
    ]
