# Generated by Django 2.1.5 on 2019-03-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190310_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrdersNC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaidOrdersNC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaidOrdersNC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productincart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productinmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PaidOrders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='nc_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cart'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Productinmenu'),
        ),
        migrations.AddField(
            model_name='paidordersnc3',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Cart'),
        ),
        migrations.AddField(
            model_name='paidordersnc2',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Cart'),
        ),
        migrations.AddField(
            model_name='paidordersnc1',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Cart'),
        ),
    ]
