# Generated by Django 2.1.7 on 2019-03-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190324_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidordersnc1',
            old_name='item_name',
            new_name='order_details',
        ),
        migrations.RenameField(
            model_name='paidordersnc2',
            old_name='item_name',
            new_name='order_details',
        ),
        migrations.RenameField(
            model_name='paidordersnc3',
            old_name='item_name',
            new_name='order_details',
        ),
        migrations.RemoveField(
            model_name='paidordersnc1',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paidordersnc1',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='paidordersnc2',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paidordersnc2',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='paidordersnc3',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paidordersnc3',
            name='quantity',
        ),
    ]
