# Generated by Django 2.1.7 on 2019-03-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190324_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidordersnc1',
            old_name='filters',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='paidordersnc2',
            old_name='filters',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='paidordersnc3',
            old_name='filters',
            new_name='order_status',
        ),
    ]
